# You can access these variables using jekyll template language and the
# `site` variable, e.g.: {{site.title}}
# Look at layouts/default.html to see how they are used

title: My Page
description: My github page
#logo_url: /assets/images/uptane-logo-white.png
google_analytics: false
theme: jekyll-theme-cayman
exclude: ["LICENSE", "README.md"]

plugins:
  - jekyll-mentions